           - name: terraform-plan-storage
  uses: cloudposse/github-action-terraform-plan-storage@1.14.0
  with:
    action: storePlan # Define the action, e.g., storePlan, getPlan, or taintPlan
    bucketName: your-s3-bucket-name # Replace with your S3 bucket name
    planPath: ./terraform.plan # Provide the path to the Terraform plan file
    planRepositoryType: s3 # Type of repository where the plan is stored ('s3' or 'azureblob')
    component: my-component-name # (Optional) Name of the component for the plan file
    failOnMissingPlan: true # Fail if the plan is missing (default: true)
    metadataRepositoryType: dynamo # Metadata repository type ('dynamo' or 'cosmosdb')

    stack: # optional
    # the name of the dynamodb table to store metadata
    tableName: # optional, default is terraform-plan-storage
          
